trigger:
  branches:
    include:
      - main                        #targets main branch as the source for CI trigger
  paths:
    exclude:
      - azure-pipelines.yml
      - README.md

name: Client Portal Azure Envrionment

pool:
  vmImage: windows-latest

variables:
  environmentResourceGroup: 'gt-st-d365portal-rg' #Name of the resource group in which the other resources get deployed except subnets. Differs per environment
  azureSubscription: 'GTCAGTWay-conn-st-d365-portal'  #Azure service connection used by the pipline. Differs per environment


steps:
  - task: AzureCLI@2
    timeoutInMinutes: 120
    displayName: 'Deploy Client Portal Azure environment'
    inputs:
      azureSubscription: $(azureSubscription)
      scriptType: 'pscore'
      scriptLocation: 'inlineScript'
      inlineScript: |
        az login --service-principal  -u $env:servicePrincipalId -p $env:servicePrincipalKey --tenant $env:tenantId
        az deployment group create --resource-group $(environmentResourceGroup) --template-file main.bicep --parameters main.parameters.jsonc
      addSpnToEnvironment: true
      failOnStandardError: false
